SELECT COUNT(DISTINCT o.ID) AS TOTAL_COUNT
 FROM PETEL_ORDERS o
 LEFT JOIN PETEL_ORDER_ITEMS oi ON o.ID = oi.ORDER_ID
 LEFT JOIN PETEL_USERS u ON o.USER_ID = u.ID
 LEFT JOIN PETEL_PROPERTY p ON o.PROPERTY_ID = p.ID
 LEFT JOIN PETEL_ROOMS r ON oi.ROOM_ID = r.ID
 WHERE 1=1
 [AND o.ID LIKE :orderId ]
 [AND oi.ARRIVAL_DATE = :checkIn ]
 [AND ( o.GUEST_NAME LIKE :userName OR u.NAME LIKE :userName ) ]
 [AND ( o.GUEST_PHONE = :userPhone OR u.PHONE = :userPhone ) ]
 [AND p.NAME LIKE :propertyName ]
 [AND p.TEL = :propertyPhone ]
