SELECT
    p.ID AS PROPERTY_ID,
    p.NAME AS PROPERTY_NAME,
    p.TEL AS TEL,
    p.POSTAL_CODE AS POSTAL_CODE,
    p.ADDRESS,
    p.BANK_ACCOUNT AS BANK_ACCOUNT,
    s.NAME AS SELLER_NAME,
    s.BUSINESS_CODE
FROM
    PETEL_PROPERTY p
LEFT JOIN
    PETEL_SELLERS s ON p.SELLER_ID = s.ID
WHERE
    1=1
    [AND p.NAME LIKE :propertyName]
    [AND p.TEL LIKE :tel]
    [AND p.POSTAL_CODE LIKE :postalCode]
    [AND p.ADDRESS LIKE :address]
    [AND s.NAME LIKE :sellerName]
ORDER BY p.ID
OFFSET :offset ROWS FETCH NEXT :pageSize ROWS ONLY
