SELECT
    p.PROPERTY_ID AS PROPERTY_ID,
    p.PROPERTY_NAME AS PROPERTY_NAME,
    p.PROPERTY_TEL,
    p.PROPERTY_POSTAL_CODE,
    p.PROPERTY_ADDRESS,
    p.PROPERTY_BANK_ACCOUNT,
    s.SELLERS_NAME AS SELLER_NAME,
    s.BUSINESS_CODE
FROM
    PETEL_PROPERTY p
LEFT JOIN
    PETEL_SELLERS s ON p.SELLER_ID = s.SELLERS_ID
WHERE
    1=1
    [AND p.PROPERTY_NAME LIKE :propertyName]
    [AND p.PROPERTY_TEL LIKE :tel]
    [AND p.PROPERTY_POSTAL_CODE LIKE :postalCode]
    [AND p.PROPERTY_ADDRESS LIKE :address]
    [AND s.SELLERS_NAME LIKE :sellerName]
