SELECT
    o.ID AS ORDER_ID,
--    oi.ARRIVAL_DATE AS STAY_DATE,
    o.GUEST AS GUEST,
    o.GUEST_NAME AS GUEST_NAME,
    o.GUEST_PHONE AS GUEST_PHONE,
    o.CHECK_IN,
    o.CHECK_OUT,
    o.HOTEL_CHARGES,
    u.NAME AS USER_NAME,
    u.PHONE AS USER_PHONE,
    p.NAME AS PROPERTY_NAME,
    p.TEL AS PROPERTY_PHONE,
    LISTAGG(DISTINCT r.NAME, ', ') WITHIN GROUP (ORDER BY r.NAME) AS ROOM,
    COUNT(DISTINCT oi.ROOM_ID) AS QUANTITY,
--    oi.PRICE AS PRICE_EVERYNIGHT,
    o.STATUS AS STATUS,
    o.NOTE AS NOTE,
    TO_CHAR(o.CREATED_AT, 'YYYY-MM-DD') AS CREATED_AT,
    TO_CHAR(o.UPDATED_AT, 'YYYY-MM-DD') AS UPDATED_AT,
    y.name as PAYMENT_METHOD
 FROM PETEL_ORDERS o
         LEFT JOIN PETEL_ORDER_ITEMS oi ON o.ID = oi.ORDER_ID
         LEFT JOIN PETEL_USERS u ON o.USER_ID = u.ID
         LEFT JOIN PETEL_PROPERTY p ON o.PROPERTY_ID = p.ID
         LEFT JOIN PETEL_ROOMS r ON oi.ROOM_ID = r.ID
         LEFT JOIN PETEL_PAYMENT y ON o.PAYMENT_ID = y.ID
 WHERE 1=1

  [AND o.ID LIKE :orderId ]
  [AND oi.ARRIVAL_DATE = :checkIn ]
  [AND ( o.GUEST_NAME LIKE :userName OR u.NAME LIKE :userName ) ]
  [AND ( o.GUEST_PHONE = :userPhone OR u.PHONE = :userPhone ) ]
  [AND p.NAME LIKE :propertyName ]
  [AND p.TEL = :propertyPhone ]
 GROUP BY o.ID, o.GUEST, o.GUEST_NAME, o.GUEST_PHONE, o.CHECK_IN, o.CHECK_OUT,
    o.HOTEL_CHARGES, u.NAME, u.PHONE, p.NAME, p.TEL, o.STATUS, o.NOTE,
    o.CREATED_AT, o.UPDATED_AT, y.name
  ORDER BY o.ID DESC
  OFFSET :offset ROWS FETCH NEXT :pageNumber ROWS ONLY

