SELECT
    ID          AS MESSAGE_ID,
    SENDER_ID   AS SENDER_ID,
    TYPE        AS TYPE,
    CONTENT     AS CONTENT,
    CREATED_AT  AS CREATED_AT
FROM PETEL_CHAT_MESSAGES
WHERE THREAD_ID = :threadId
ORDER BY CREATED_AT DESC
OFFSET :offset ROWS FETCH NEXT :limit ROWS ONLY