SELECT COUNT(*) AS HAS_INVENTORY
FROM PETEL_ROOM_INVENTORIES ri
INNER JOIN PETEL_ROOMS rm ON ri.ROOM_ID = rm.ID
WHERE ri.STAY_DATE >= :checkIn
  AND ri.STAY_DATE < :checkOut
  AND rm.PET_TYPE_ID = :petType
