SELECT
    pi.PROPERTY_ID,
    pi.MEDIA_ID,
    pi.SORT_ORDER,
    mb.BASE64_DATA,
    mb.FILE_NAME,
    mb.MIME_TYPE
FROM PETEL_PROPERTY_IMAGE pi
INNER JOIN PETEL_MEDIA_BASE64 mb ON pi.MEDIA_ID = mb.ID
WHERE pi.PROPERTY_ID IN (:propertyIds)
  AND pi.SORT_ORDER = 1  -- 只查詢封面照（sortOrder = 1）
ORDER BY pi.PROPERTY_ID
