--MERCH003_QUERY
SELECT
  T1.ID,
  T1.ORDER_ID,
  T2.NAME AS USER_NAME,
  T1.PRICE_SCORE,
  T1.ENV_SCORE,
  T1.SERVICE_SCORE,
  T1.CONTENT,
  T1.CREATED_AT,
  COUNT(1) OVER() AS TOTAL_COUNT
FROM PETEL_REVIEWS T1
LEFT JOIN PETEL_USERS T2 ON T1.USER_ID = T2.ID
LEFT JOIN PETEL_PROPERTY T3 ON T1.PROPERTY_ID = T3.ID
WHERE T1.PROPERTY_ID = :propertyId
ORDER BY T1.ID
OFFSET :offset ROWS FETCH NEXT :pageSize ROWS ONLY
