--MERCH001_QUERY
SELECT
 T1.ID,
 T1.CREATED_AT,
 T2.NAME AS USER_NAME,
 T1.CHECK_IN,
 T1.CHECK_OUT,
 T4.NAME AS PAYMENT_NAME,
 T1.STATUS,
 T1.HOTEL_CHARGES,
 COUNT(1) OVER() AS TOTAL_COUNT
FROM PETEL_ORDERS T1
LEFT JOIN PETEL_USERS T2 ON T1.USER_ID = T2.ID
LEFT JOIN PETEL_PROPERTY T3 ON T1.PROPERTY_ID = T3.ID
LEFT JOIN PETEL_PAYMENT T4 ON T1.PAYMENT_ID = T4.ID
WHERE T1.PROPERTY_ID = :propertyId
ORDER BY T1.ID
OFFSET :offset ROWS FETCH NEXT :pageSize ROWS ONLY
